replicaCount: 1

image:
  repository: janohjr/web-app
  pullPolicy: IfNotPresent
  tag: "18374421705"

ingress:
  enabled: false
  className: ""
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"

  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
