apiVersion: v1
kind: Service
metadata:
  name: web-app-svc
  labels:
    app: web-app-svc
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
