# This workflow will build a golang project
name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "helm/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "helm/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Set Up Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Download dependencies
        run: go mod download

      - name: build go
        run: go build -o web-app

      - name: Test
        run: go test ./...

  code-quality:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Run golangCi-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1

  docker-build-push:
    runs-on: ubuntu-latest

    needs: code-quality

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/web-app:${{ github.run_id }}

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest

    needs: docker-build-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update Helm Chart
        run: |
          sed -i 's/tag: .*/tag: "${{ github.run_id }}"/' helm/web-app-chart/values.yaml

      - name: Commit and Push changes
        run: |
          git config  user.email "frujuniorp@gmail.com"
          git config  user.name "Fru Junior"
          git add .
          git commit -m "Update tag in Helm Chart"
          git push
